apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: syslog-reader-set
  namespace: volume-part1
spec:
  selector:
    matchLabels:
      app: syslog-reader
  template:
    metadata:
      labels:
        app: syslog-reader
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        # command: [ "sh", "-c", "tail -f /var/log/syslog" ]
        volumeMounts:
        - name: syslog-volume
          mountPath: /log-data/123
      volumes:
      - name: syslog-volume
        hostPath:
          path: /var/log/syslog